
const ratings=['◎','〇','△','×'];
let state={shops:[],visits:[],photos:[],tab:'shops',query:'',area:'all',selectedShopId:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=s=>{if(!s)return'';const d=new Date(s+'T00:00:00');return `${d.getFullYear()}/${d.getMonth()+1}/${d.getDate()}`};
function latestVisit(shopId){return state.visits.filter(v=>v.shop_id===shopId).sort((a,b)=>String(b.visited_on).localeCompare(String(a.visited_on)))[0]||null}
function photosFor(visitId){return state.photos.filter(p=>p.visit_id===visitId)}
function totalCount(shop){const n=state.visits.filter(v=>v.shop_id===shop.id).length;return Math.max(n,Number(shop.legacy_count||0))}
function render(){
  const visitedShopIds=new Set(state.visits.map(v=>v.shop_id));
  $('#statShops').textContent=state.shops.length;$('#statVisited').textContent=visitedShopIds.size;$('#statUnvisited').textContent=state.shops.length-visitedShopIds.size;$('#statVisits').textContent=state.visits.length;
  const areas=[...new Set(state.shops.map(s=>s.area).filter(Boolean))].sort();
  const areaSel=$('#areaFilter'); const cur=state.area; areaSel.innerHTML='<option value="all">全地域</option>'+areas.map(a=>`<option>${esc(a)}</option>`).join(''); areaSel.value=areas.includes(cur)?cur:'all';
  $$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));
  $('#shopsView').classList.toggle('hidden',state.tab!=='shops');$('#historyView').classList.toggle('hidden',state.tab!=='history');$('#settingsView').classList.toggle('hidden',state.tab!=='settings');
  $('#fab').classList.toggle('hidden',state.tab==='settings');
  if(state.tab==='shops')renderShops(); if(state.tab==='history')renderHistory();
}
function filteredShops(){const q=state.query.trim().toLowerCase();return state.shops.filter(s=>(state.area==='all'||s.area===state.area)&&(!q||`${s.name} ${s.area}`.toLowerCase().includes(q))).sort((a,b)=>a.area.localeCompare(b.area,'ja')||a.name.localeCompare(b.name,'ja'))}
function renderShops(){const list=filteredShops();$('#shopList').innerHTML=list.length?list.map(s=>{const v=latestVisit(s.id);return `<button class="card shop-card" style="width:100%;text-align:left" data-shop="${s.id}"><div><div class="shop-name">${esc(s.name)}</div><div class="meta">${esc(s.area)} ・ ${v?`最終 ${fmtDate(v.visited_on)} ・ ${totalCount(s)}回`:'未訪問'}</div>${v?`<div class="ratings"><span class="ratechip">スープ ${esc(v.soup)}</span><span class="ratechip">麺 ${esc(v.noodle)}</span><span class="ratechip">再訪 ${esc(v.revisit)}</span></div>`:'<div class="meta unvisited">行ってみたい店</div>'}</div><div class="chev">›</div></button>`}).join(''):'<div class="empty">該当する店がありません</div>';$$('[data-shop]').forEach(b=>b.onclick=()=>openShop(b.dataset.shop));}
function renderHistory(){const q=state.query.trim().toLowerCase();const rows=[...state.visits].sort((a,b)=>String(b.visited_on).localeCompare(String(a.visited_on))).filter(v=>{const s=state.shops.find(x=>x.id===v.shop_id);return s&&(state.area==='all'||s.area===state.area)&&(!q||`${s.name} ${s.area} ${v.menu} ${v.comment}`.toLowerCase().includes(q))});$('#historyList').innerHTML=rows.length?rows.map(v=>visitCard(v,true)).join(''):'<div class="empty">訪問記録がありません</div>';}
function visitCard(v,withShop=false){const s=state.shops.find(x=>x.id===v.shop_id);const ps=photosFor(v.id);return `<article class="card"><div class="visit-date">${fmtDate(v.visited_on)}${withShop&&s?` ・ ${esc(s.area)} / <b>${esc(s.name)}</b>`:''}</div><div class="visit-menu">${esc(v.menu||'メニュー未記入')}</div><div class="ratings"><span class="ratechip">スープ ${esc(v.soup||'-')}</span><span class="ratechip">麺 ${esc(v.noodle||'-')}</span><span class="ratechip">再訪 ${esc(v.revisit||'-')}</span></div>${v.comment?`<div class="comment">${esc(v.comment)}</div>`:''}${ps.length?`<div class="thumbs">${ps.map(p=>`<img src="${esc(p.url)}" alt="ラーメン写真" loading="lazy">`).join('')}</div>`:''}</article>`}
function openShop(id){state.selectedShopId=id;const s=state.shops.find(x=>x.id===id);if(!s)return;$('#shopDialogTitle').textContent=s.name;$('#shopDialogMeta').textContent=`${s.area} ・ ${totalCount(s)}回`;const vs=state.visits.filter(v=>v.shop_id===id).sort((a,b)=>String(b.visited_on).localeCompare(String(a.visited_on)));$('#shopVisits').innerHTML=vs.length?vs.map(v=>visitCard(v)).join(''):'<div class="empty">まだ訪問記録がありません</div>';$('#addVisitForShop').onclick=()=>{shopDialog.close();openVisitForm(id)};shopDialog.showModal();}
function ratingHTML(name,label){return `<div class="field"><label>${label}</label><div class="rating-select">${ratings.map((r,i)=>`<label><input type="radio" name="${name}" value="${r}" ${i===1?'checked':''}><span>${r}</span></label>`).join('')}</div></div>`}
function openVisitForm(shopId=''){const sel=$('#visitShop');sel.innerHTML='<option value="">店を選択</option>'+state.shops.slice().sort((a,b)=>a.name.localeCompare(b.name,'ja')).map(s=>`<option value="${s.id}">${esc(s.area)}｜${esc(s.name)}</option>`).join('');sel.value=shopId||'';$('#visitDate').value=new Date().toISOString().slice(0,10);$('#visitMenu').value='';$('#visitComment').value='';$('#visitPhotos').value='';visitDialog.showModal();}
function openShopForm(){ $('#newShopArea').value='';$('#newShopName').value='';shopFormDialog.showModal(); }
function bindUI(){
  $('#search').oninput=e=>{state.query=e.target.value;render()};$('#areaFilter').onchange=e=>{state.area=e.target.value;render()};
  $$('.navbtn').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});$('#fab').onclick=()=>openVisitForm();$('#addShopBtn').onclick=openShopForm;
  $$('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
}

import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';
import { SEED } from './seed.js';
const configured=SUPABASE_URL&&!SUPABASE_URL.includes('YOUR_')&&SUPABASE_ANON_KEY&&!SUPABASE_ANON_KEY.includes('YOUR_');
let supabase=null,user=null;
function setNotice(msg,type=''){const n=$('#notice');n.textContent=msg;n.className='notice '+(type==='error'?'error':type==='ok'?'oknotice':'');n.classList.toggle('hidden',!msg)}
async function seedIfEmpty(){const {count,error}=await supabase.from('shops').select('*',{count:'exact',head:true});if(error)throw error;if(count>0)return;const shopRows=SEED.shops.map(s=>({id:crypto.randomUUID(),seed_id:s.id,user_id:user.id,area:s.area,name:s.name,legacy_count:s.legacy_count||0}));const idMap=Object.fromEntries(shopRows.map((s,i)=>[SEED.shops[i].id,s.id]));let r=await supabase.from('shops').insert(shopRows);if(r.error)throw r.error;const visitRows=SEED.visits.map(v=>({id:crypto.randomUUID(),user_id:user.id,shop_id:idMap[v.shop_id],visited_on:v.visited_on,menu:v.menu,soup:v.soup,noodle:v.noodle,revisit:v.revisit,comment:v.comment}));if(visitRows.length){r=await supabase.from('visits').insert(visitRows);if(r.error)throw r.error}}
async function loadCloud(){if(!user)return;let {data:shops,error}=await supabase.from('shops').select('*').order('area').order('name');if(error)throw error;let {data:visits,error:e2}=await supabase.from('visits').select('*').order('visited_on',{ascending:false});if(e2)throw e2;let {data:photos,error:e3}=await supabase.from('visit_photos').select('*');if(e3)throw e3;const signed=await Promise.all((photos||[]).map(async p=>{const {data}=await supabase.storage.from('ramen-photos').createSignedUrl(p.path,3600);return {...p,url:data?.signedUrl||''}}));state.shops=shops||[];state.visits=visits||[];state.photos=signed.filter(p=>p.url);render();}
async function refreshAuth(){const {data:{session}}=await supabase.auth.getSession();user=session?.user||null;$('#authBox').classList.toggle('hidden',!!user);$('#appContent').classList.toggle('hidden',!user);$('#userBar').classList.toggle('hidden',!user);$('#userEmail').textContent=user?.email||'';if(user){try{setNotice('初回データを確認しています…');await seedIfEmpty();await loadCloud();setNotice('')}catch(e){setNotice('読み込みエラー: '+e.message,'error')}}}
async function handleAuth(e,mode){e.preventDefault();const email=$('#email').value.trim(),password=$('#password').value;if(!email||password.length<6)return setNotice('メールアドレスと6文字以上のパスワードを入力してください','error');setNotice(mode==='signup'?'アカウントを作成しています…':'ログインしています…');const res=mode==='signup'?await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}}):await supabase.auth.signInWithPassword({email,password});if(res.error)return setNotice(res.error.message,'error');if(mode==='signup'&&!res.data.session){setNotice('確認メールを送りました。メール内のリンクを開いてからログインしてください。','ok')}else{setNotice('');await refreshAuth()}}
async function handleVisitSubmit(e){e.preventDefault();const shop_id=$('#visitShop').value;if(!shop_id)return alert('店を選んでください');const fd=new FormData(e.target),row={user_id:user.id,shop_id,visited_on:$('#visitDate').value,menu:$('#visitMenu').value.trim(),soup:fd.get('soup'),noodle:fd.get('noodle'),revisit:fd.get('revisit'),comment:$('#visitComment').value.trim()};let {data,error}=await supabase.from('visits').insert(row).select().single();if(error)return alert(error.message);const files=[...$('#visitPhotos').files].slice(0,5);for(const file of files){const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'').toLowerCase();const path=`${user.id}/${data.id}/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from('ramen-photos').upload(path,file,{upsert:false});if(up.error){alert('写真のアップロードに失敗しました: '+up.error.message);continue}const pr=await supabase.from('visit_photos').insert({user_id:user.id,visit_id:data.id,path});if(pr.error)alert('写真情報の保存に失敗しました: '+pr.error.message)}visitDialog.close();await loadCloud()}
async function handleShopSubmit(e){e.preventDefault();const name=$('#newShopName').value.trim();if(!name)return;const {error}=await supabase.from('shops').insert({user_id:user.id,area:$('#newShopArea').value.trim(),name,legacy_count:0});if(error)return alert(error.message);shopFormDialog.close();await loadCloud()}
async function exportBackup(){const payload={exported_at:new Date().toISOString(),shops:state.shops,visits:state.visits,photos:state.photos.map(({url,...p})=>p)};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ramen-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
window.addEventListener('DOMContentLoaded',async()=>{bindUI();$('#visitForm').onsubmit=handleVisitSubmit;$('#shopForm').onsubmit=handleShopSubmit;$('#backupBtn').onclick=exportBackup;if(!configured){$('#configMissing').classList.remove('hidden');$('#authBox').classList.add('hidden');$('#appContent').classList.add('hidden');$('#fab').classList.add('hidden');return}supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);$('#loginBtn').onclick=e=>handleAuth(e,'login');$('#signupBtn').onclick=e=>handleAuth(e,'signup');$('#logoutBtn').onclick=async()=>{await supabase.auth.signOut();await refreshAuth()};supabase.auth.onAuthStateChange(()=>setTimeout(refreshAuth,0));await refreshAuth();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});});
